### ISSUE TITLE
key-store add head bytes

### ISSUE THREAD

**Issue by jingpengwu** [joshbode/GoogleCloud.jl#9]
The KeyStore added 10 extra head bytes in binary files, right?
we need to skip the first 10 bytes to decompress the binary files in python.

Dose it come from serialization?

https://github.com/joshbode/GoogleCloud.jl/blob/master/src/collection.jl#L16

**Comment by joshbode** [comment]
I don't believe `KeyStore` serialisation is adding anything particular - it is probably Libz adding the gzip header.

This is effectively what is being done in `KeyStore` when `gzip=true` (default):
```julia
data = collect(0x00:0xff)
open("/tmp/foo.gz", "w") do f
    write(f, read(Libz.ZlibDeflateInputStream(data)))
end
```
which `gunzip`s happily:
```bash
$ gunzip -c /tmp/foo.gz > /tmp/foo
```

In Python using `gzip`:
```python
import gzip
with gzip.open("/tmp/foo.gz", "r") as f:
    data = f.read()
assert data == ''.join(chr(i) for i in range(256))
```
or with `zlib` (which needs to be told it is in gzip format: `zlib.MAX_WBITS | 16`)
```python
import zlib
with open("/tmp/foo.gz", "r") as f:
    data = zlib.decompress(f.read(), zlib.MAX_WBITS | 16)
assert data == ''.join(chr(i) for i in range(256))
```

**Comment by joshbode** [comment]
How are you decompressing in Python?

**Comment by joshbode** [comment]
However, depending upon what you're using to get the objects in Python (`requests`?), I imagine you should be able to transparently decompress the data using the HTTP client due to the way it has been stored in storage (with `contentEncoding = "gzip"`, which should make the HTTP response to the object get have header `Content-Encoding: gzip`) facilitating decompressive transcoding (see https://cloud.google.com/storage/docs/transcoding)

**Comment by joshbode** [comment]
If you _are_ using `zlib.decompress`, from http://www.zlib.net/manual.html:
> Add 32 to windowBits to enable zlib and gzip decoding with automatic header detection,
> or add 16 to decode only the gzip format

which explains the `16` in the zlib flag in the Python example above

**Comment by jingpengwu** [comment]
I should make it clear first. I was using Blosc.jl to compress the array first and saved in GCS without using gzip.

**Comment by jingpengwu** [comment]
I just did a simple test. The data is a simple vector, and Libz compressed is 24 bytes, which is the same with python gzip compression. After uploading it with KeyStore, there is an extra 2 head bytes: 0x15,0x93. Skipping these two bytes works with this test.

```
using GSDicts
using Libz
a = Vector{UInt8}([0,1,2,3])
data2 = Libz.compress(a)
write("test.local.libz", data2)

d2 = GSDict("gs://jpwu/test/")

d2["test.libz"] = data2

Libz.decompress(data2)

f = open(joinpath(dirname(@__FILE__()), "../assets/test.libz"))
data3 = read(f)
close(f)

Libz.decompress(data3[3:end])

```
![image](https://cloud.githubusercontent.com/assets/7651573/23713975/a5d2e7e0-03f5-11e7-9cbd-b983fdabe26f.png)

**Comment by jingpengwu** [comment]
adding `identity` function for serialization solved this problem. 
https://github.com/jingpengwu/GoogleCloud.jl/commit/e65b0c93c7bb7ab8eed33f9d1880e3589d60d5ba?diff=unified

**Comment by joshbode** [comment]
Ahh - understood. I don't use the Julia (de)serialiser much - mostly using gzipped MsgPack (much faster and smaller than JSON with much the same feature set).

BTW, the only reason that GoogleCloud.jl is gzipping explicitly rather than using the compression built into Requests.jl is that I couldn't get Google Storage to correctly interpret uploaded data as being gzipped if the header `Content-Encoding: gzip` is present on upload, which is why I add the parameter `contentEncoding=gzip` instead. That way, when pulling the data back from storage, the HTTP client can request `Accept-Encoding: gzip`, Google Storage will deliver the stored, gzipped data directly and the client will decompress the response for me :)

**Comment by joshbode** [comment]
Also, off topic: which editor is that?

**Comment by jingpengwu** [comment]
It is atom with Juno.
http://junolab.org/
